# Generated by Django 4.1.5 on 2023-07-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
